tunnel() {
	lt --port $1
}

git:reset-branch-remote() {
	git fetch origin
git reset --hard origin/$1
}

git:reset-file() {
	git checkout HEAD -- $1
}

exec:it() {
	docker exec -it $1 $2
}

algomo:build() {
	docker compose -f example-docker-compose.local.yml build ${@:1}
}

algomo:up() {
	docker compose -f example-docker-compose.local.yml up ${@:1}
}